import type { ProviderId } from "../types.js";
import { FAMILYLESS_ENDPOINT_LAYERS } from "./provider-profile-layers.js";

export const REASONING_PATTERNS: Record<ProviderId, RegExp[]> = {
  free: [/deepseek/i, /kimi/i, /minimax/i, /mimo/i, /nemotron/i],
  gemini: [/gemini-2\.5/i, /gemini-3/i, /gemini-3\.5/i],
  openrouter: [
    /:thinking/i,
    /deepseek-r1/i,
    /qwen3/i,
    /kimi-k2/i,
    /claude-(?:opus|sonnet|haiku)-4/i,
    /gpt-5/i,
    /o[134]/i,
    /grok.*reasoner/i,
  ],
  openai: [/gpt-5/i, /o1/i, /o3/i, /o4/i],
  anthropic: [/claude-(?:opus|sonnet|haiku)-(?:3-7|4|4-\d)/i, /claude-3-7/i],
  nvidia: [
    /kimi-k2/i,
    /deepseek-r1/i,
    /deepseek-v[34]/i,
    /qwen3/i,
    /nemotron/i,
    /glm-?5/i,
    /gpt-oss/i,
  ],
  ollama: [/deepseek-r1/i, /qwen3/i, /qwq/i],
  agentrouter: [
    /gpt-5/i,
    /gpt-6/i,
    /claude-(?:opus|sonnet|haiku)-4/i,
    /deepseek-(?:v[34]|r1)/i,
    /glm-?[45]/i,
    /qwen3/i,
    /kimi-k2/i,
    /o[134]/i,
  ],
  "aws-mantle": [/claude-(?:opus|sonnet|haiku)-4/i],
  bynara: [/kimi/i, /deepseek/i, /agnes/i, /stepfun/i, /qwen/i],
  "qwen-cloud": [/qwen3/i, /qwen2/i],
  modal: [
    /kimi/i,
    /qwen3/i,
    /deepseek/i,
    /glm-?[45]/i,
    /gpt-oss/i,
    /nemotron/i,
    /gemma-?[34]/i,
  ],
  lightning: [
    /gpt-5/i,
    /o[134](?:-mini)?\b/i,
    /claude-(?:opus|sonnet|haiku)-4/i,
    /claude-fable/i,
    /gemini-3/i,
    /gemini-2\.5/i,
    /deepseek/i,
    /gpt-oss/i,
    /nemotron/i,
  ],
  tokenrouter: [
    /kimi/i,
    /deepseek/i,
    /qwen3/i,
    /glm-?[45]/i,
    /gpt-oss/i,
    /minimax/i,
    /gpt-[56]/i,
    /o[134](?:-mini)?\b/i,
    /claude-(?:opus|sonnet|haiku)/i,
    /gemini-(?:2\.5|3)/i,
    /grok-(?:4\.[3-9]|[5-9])/i,
    /mistral-(?:medium|small|large)-\d/i,
    /nemotron/i,
  ],
  meta: [/muse-spark/i],
  fireworks: [/kimi/i, /deepseek/i, /qwen3/i, /glm-?5/i, /gpt-oss/i, /nemotron/i, /minimax/i, /mimo/i],
  hetzner: [/qwen3/i, /qwen/i],
  orcarouter: [
    /o[134]/i,
    /gpt-5/i,
    /claude-(?:opus|sonnet)/i,
    /gemini-2\.5|gemini-3/i,
    /deepseek-reasoner/i,
    /grok.*reason/i,
    /qwen3/i,
    /kimi/i,
    /glm/i,
  ],
  "merge-gateway": [
    /o[134]/i,
    /gpt-5/i,
    /gpt-oss/i,
    /claude-(?:opus|sonnet|haiku)/i,
    /gemini-2\.5|gemini-3/i,
    /deepseek-(?:r1|v[34]|reasoner)/i,
    /qwen3/i,
    /glm-?[45]/i,
    /kimi/i,
    /minimax/i,
    /mimo/i,
    /nemotron/i,
    /nova/i,
    /dola-seed/i,
    /inkling/i,
    /magistral/i,
    /thinking/i,
    /grok-.*reasoning|grok-4\.[3-9]|grok-[5-9]/i,
  ],
  explabs: [
    /claude-(?:fable|opus|sonnet|haiku)/i,
    /gpt-5/i,
    /gpt-6/i,
    /gemini-/i,
    /kimi/i,
    /glm/i,
    /deepseek/i,
    /qwen3/i,
    /aion/i,
  ],
};

export function endpointAcceptedEfforts(
  provider: ProviderId,
): readonly string[] | undefined {
  const efforts =
    FAMILYLESS_ENDPOINT_LAYERS[provider]?.reasoning?.acceptedEfforts;
  return efforts && efforts.length > 0 ? efforts : undefined;
}
