import type { ProviderId } from "../../types.js";

export const textOnlyPatterns: RegExp[] = [
  /(?:^|\/)glm-?5(?:(?:\.|p)[123])?(?:-fast)?$/i,
];

export const universalVisionPatterns: RegExp[] = [
  /(?:^|[-/_.])vision(?:$|[-_.])/i,
  /(?:^|[-/_.])vl(?:$|[-_.])/i,
  /multimodal/i,
  /omni(?:$|[-_.])/i,
  /llava/i,
  /bakllava/i,
  /moondream/i,
  /minicpm-?v/i,
  /internvl/i,
  /pixtral/i,
  /paligemma/i,
  /florence-2/i,
  /molmo/i,
  /kosmos/i,
  /fuyu/i,
  /idefics/i,
  /aya-vision/i,
  /granite.*vision/i,
  /smolvlm/i,
  /llama-?4/i,
  /llama-?3\.2-(?:11b|90b)/i,
  /gemma-?[34](?!\D*\b1b)/i,
  /qwen-?vl/i,
  /qwen\d*(?:\.\d+)?-?vl/i,
  /gpt-4o/i,
  /gpt-4\.1/i,
  /gpt-4-turbo/i,
  /gpt-5/i,
  /gemini-/i,
  /claude-3(?:[-.]|$)/i,
  /claude-(?:opus|sonnet|haiku)-(?:[3-9]|\d{2,})/i,
  /grok-(?:[4-9]|\d{2,})/i,
  /mistral-(?:small|medium|large)-3/i,
  /magistral-(?:small|medium)/i,
  /phi-(?:4|5)-multimodal/i,
  /nova-(?:lite|pro|premier)/i,
  /step-1[ov]/i,
  /ernie-\d+(?:\.\d+)?-vl/i,
  /glm-4\.?\d*v/i,
  /kimi-k2\.\d/i,
  /kimi-k[3-9]/i,
];

export const visionPatterns: Record<ProviderId, RegExp[]> = {
  free: [],
  gemini: [
    /gemini-/i,
  ],
  openrouter: [
    /gpt-4o/i,
    /gpt-4\.1/i,
    /gpt-5/i,
    /claude-(?:opus|sonnet|haiku)-(?:3-5|3-7|4|4-\d)/i,
    /claude-3(?:-|\.|$)/i,
    /gemini-/i,
    /llama-4/i,
    /llama-3\.2-(?:11b|90b)-vision/i,
    /qwen2?\.?5?-vl/i,
    /pixtral/i,
    /grok-(?:2-)?vision/i,
    /grok-4/i,
    /:vision/i,
  ],
  openai: [/gpt-4o/i, /gpt-4\.1/i, /gpt-5/i, /o[34]/i, /gpt-4-turbo/i],
  anthropic: [
    /claude-(?:opus|sonnet|haiku)-(?:3|3-5|3-7|4|4-\d)/i,
    /claude-3(?:-|\.|$)/i,
  ],
  nvidia: [
    /llama-4/i,
    /llama-3\.2-(?:11b|90b)-vision/i,
    /vila/i,
    /neva/i,
    /qwen2?\.?5?-vl/i,
    /pixtral/i,
    /gemma-3/i,
    /minimax-m3/i,
  ],
  ollama: [
    /llava/i,
    /llama3\.2-vision/i,
    /llama-?4/i,
    /bakllava/i,
    /moondream/i,
    /minicpm-?v/i,
    /qwen2?\.?5?-vl/i,
    /gemma3/i,
  ],
  agentrouter: [
    /gpt-4o/i,
    /gpt-4\.1/i,
    /gpt-5/i,
    /claude-(?:opus|sonnet|haiku)-(?:3-5|3-7|4|4-\d)/i,
    /claude-3(?:-|\.|$)/i,
    /gemini-/i,
    /llama-4/i,
    /qwen2?\.?5?-vl/i,
    /glm-4\.?\d*v/i,
  ],
  "aws-mantle": [
    /claude-(?:opus|sonnet|haiku)-(?:3|3-5|3-7|4|4-\d)/i,
    /claude-3(?:-|\.|$)/i,
    /gpt-4o/i,
    /gpt-4\.1/i,
    /gpt-5/i,
    /gemini-/i,
    /llama-4/i,
    /qwen2?\.?5?-vl/i,
    /qwen-vl/i,
    /glm-4\.?\d*v/i,
    /vision/i,
  ],
  bynara: [/mimo-v2\.5/i, /mistral-medium-3-5/i, /agnes-\d/i],
  "qwen-cloud": [
    /qwen3\.7-(?:plus|max)/i,
    /qwen3\.5-(?:plus|flash)/i,
    /qwen-vl/i,
  ],
  modal: [/-vl\b/i, /-vl-/i],
  tokenrouter: [/kimi/i, /qwen3p\d/i, /minimax-m3/i],
  lightning: [
    /gpt-4o/i,
    /gpt-4\.1/i,
    /gpt-5/i,
    /o[34]\b/i,
    /claude-(?:opus|sonnet|haiku)-(?:3|3-5|3-7|4|4-\d)/i,
    /claude-fable/i,
    /gemini-/i,
    /gemma-4/i,
  ],
  meta: [/muse-spark/i],
  fireworks: [
    /kimi-k2/i,
    /qwen3.*vl/i,
    /qwen.*vl/i,
    /vision/i,
    /vl$/i,
    /llama-4/i,
    /pixtral/i,
    /glm-4.*v/i,
  ],
  hetzner: [/qwen/i, /vision/i, /vl/i],
  orcarouter: [
    /gpt-4o/i,
    /gpt-4\.1/i,
    /gpt-5/i,
    /claude-(?:opus|sonnet|haiku)/i,
    /gemini-/i,
    /grok-/i,
    /qwen.*vl/i,
    /kimi/i,
    /vision/i,
    /vl$/i,
  ],
  "merge-gateway": [
    /gpt-4o/i,
    /gpt-4\.1/i,
    /gpt-5/i,
    /claude-(?:opus|sonnet|haiku)/i,
    /gemini-/i,
    /llama-4/i,
    /pixtral/i,
    /vision/i,
    /vl$/i,
  ],
  explabs: [
    /claude-(?:fable|opus|sonnet|haiku)/i,
    /gpt-5/i,
    /gpt-6/i,
    /gemini-/i,
    /kimi/i,
    /glm-.*flash/i,
    /qwen/i,
    /vision/i,
    /vl$/i,
  ],
  vercel: [
    /gpt-4o/i,
    /gpt-4\.1/i,
    /gpt-5/i,
    /gpt-6/i,
    /claude-(?:opus|sonnet|haiku)/i,
    /gemini-/i,
    /llama-4/i,
    /vision/i,
    /vl$/i,
  ],
};

export const preferredVisionModels: Partial<Record<ProviderId, string>> = {
  gemini: "gemini-3.5-flash",
  openrouter: "google/gemini-2.5-flash",
  openai: "gpt-4o-mini",
  anthropic: "claude-3-5-haiku-latest",
  nvidia: "meta/llama-4-maverick-17b-128e-instruct",
  agentrouter: "claude-opus-4-6",
  "aws-mantle": "anthropic.claude-haiku-4-5",
  ollama: "llama3.2-vision",
  bynara: "mimo-v2.5-free",
  "qwen-cloud": "qwen3.7-plus",
  lightning: "google/gemini-3.5-flash",
  tokenrouter: "moonshotai/kimi-k2.7-code",
  meta: "muse-spark-1.2",
  fireworks: "accounts/fireworks/models/kimi-k2p6",
  hetzner: "Qwen/Qwen3.6-35B-A3B-FP8",
  orcarouter: "openai/gpt-4o-mini",
  "merge-gateway": "openai/gpt-5.2",
  explabs: "claude-fable-5.1",
  vercel: "openai/gpt-4o",
};
