
export const ACTION_CONTEXTS = [
  "global",
  "transcript",
  "composer",
  "picker",
  "modal",
  "secret",
  "plan",
  "transcript-search",
  "pager",
  "jobs",
] as const;

export type ActionContext = (typeof ACTION_CONTEXTS)[number];

export const ACTION_IDS = [
  "app.quit",
  "app.cancel",
  "app.interrupt",
  "app.help",
  "app.toggle-plan",
  "app.jobs",
  "app.cycle-mode",
  "app.redraw",
  "focus.next-region",
  "focus.composer",
  "focus.transcript",
  "editor.submit",
  "editor.newline",
  "editor.history-prev",
  "editor.history-next",
  "editor.clear",
  "editor.cut-draft",
  "editor.expand-paste",
  "transcript.scroll-up",
  "transcript.scroll-down",
  "transcript.page-up",
  "transcript.page-down",
  "transcript.top",
  "transcript.bottom",
  "transcript.search",
  "transcript.expand-toggle",
  "transcript.toggle-thinking",
  "transcript.copy-thinking",
  "transcript.toggle-output",
  "selection.copy",
  "selection.clear",
  "selection.select-all",
  "selection.extend-left",
  "selection.extend-right",
  "selection.extend-up",
  "selection.extend-down",
  "selection.extend-word-left",
  "selection.extend-word-right",
  "selection.extend-line-start",
  "selection.extend-line-end",
  "picker.up",
  "picker.down",
  "picker.accept",
  "picker.dismiss",
  "picker.filter",
  "modal.confirm",
  "modal.deny",
  "modal.dismiss",
  "plan.next-task",
  "plan.prev-task",
  "plan.toggle-detail",
  "queue.select-prev",
  "queue.select-next",
  "queue.send-now",
  "queue.edit",
  "queue.remove",
  "pager.line-up",
  "pager.line-down",
  "pager.page-up",
  "pager.page-down",
  "pager.half-page-up",
  "pager.half-page-down",
  "pager.top",
  "pager.bottom",
  "pager.search",
  "pager.next-match",
  "pager.prev-match",
  "pager.copy",
  "pager.toggle-follow",
  "pager.format",
  "pager.raw",
  "pager.close",
  "jobs.up",
  "jobs.down",
  "jobs.tail",
  "jobs.view-live",
  "jobs.stop",
  "jobs.close",
] as const;

export type ActionId = (typeof ACTION_IDS)[number];

export function isActionContext(value: string): value is ActionContext {
  return (ACTION_CONTEXTS as readonly string[]).includes(value);
}

export function isActionId(value: string): value is ActionId {
  return (ACTION_IDS as readonly string[]).includes(value);
}
